# Generated by Django 3.0.7 on 2020-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('file_id', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('img_url', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('main_group', models.CharField(max_length=25)),
                ('sub_group', models.CharField(max_length=25)),
                ('popularity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('new_sells', models.IntegerField()),
                ('total_sells', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('img_url', models.ImageField(upload_to='')),
                ('contact', models.TextField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
