# Generated by Django 3.0.7 on 2020-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200626_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
