# Generated by Django 3.0.7 on 2020-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200627_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='l_desc_amh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='l_desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidiet', 'Intermidiet'), ('Advanced', 'Advanced')], default='Beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='s_desc_amh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='s_desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Music_Production', 'Music_Production'), ('Programming', 'Programming'), ('Video_editing', 'Video_editing'), ('Animation&3D_modeling', 'Animation&3D_modeling'), ('English', 'English'), ('Pschology', 'Pschology'), ('Dancing', 'Dancing'), ('Painting', 'Painting'), ('Architecture', 'Architecture'), ('Graphics', 'Graphics'), ('Designing_Clothes', 'Designing_Clothes')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
