# Generated by Django 3.0.7 on 2020-07-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
