# Generated by Django 3.0.7 on 2020-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='l_desc_amh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='l_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_desc_amh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='trailer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
