# Generated by Django 3.0.7 on 2020-08-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200804_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
