# Generated by Django 3.0.7 on 2020-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('total_size', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
