# Generated by Django 3.0.7 on 2020-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_count',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='date_created',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Created', max_length=25),
        ),
    ]
